meta_product_name: "NFT-Squad"
meta_title: "NFT-Squad - Socialise on NFTs"
meta_description: "A social media platform to disocover the next trend in NFTs"
meta_image: "logo2.png" # should exist in `app/assets/images/`
